packages:
  - packages/discord.js
  - packages/rest
  - packages/ws
  - packages/core
  - packages/structures
  - packages/util
  - packages/collection
  - packages/formatters

autoInstallPeers: false

ignoredBuiltDependencies:
  - core-js-pure
  - unrs-resolver

onlyBuiltDependencies:
  - bufferutil
  - esbuild
  - protobufjs
  - utf-8-validate
  - zlib-sync

peerDependencyRules:
  allowAny:
    - '*'
  ignoreMissing:
    - '*'
