packages:
  - packages/bot
  - packages/rest
  - packages/ws
  - packages/core

  - packages/util


autoInstallPeers: false

ignoredBuiltDependencies:
  - core-js-pure
  - unrs-resolver

onlyBuiltDependencies:
  - bufferutil
  - esbuild
  - protobufjs
  - utf-8-validate
  - zlib-sync

peerDependencyRules:
  allowAny:
    - '*'
  ignoreMissing:
    - '*'
